### ISSUE TITLE
Support for graph analysis

### ISSUE THREAD

**Issue by jeppojeps** [Fare9/KUNAI-static-analyzer#6]
- CFG comparison
- Code metrics
- Similarity and reuse

**Comment by Fare9** [comment]
Added an `IRGraphSSA` class: https://github.com/Fare9/KUNAI-static-analyzer/blob/main/src/include/KUNAI/mjolnIR/Analysis/ir_graph_ssa.hpp. Added also an `Optimizer` in order to allow applying different optimizations into the IR code, this can help removing some types of obfuscations: https://github.com/Fare9/KUNAI-static-analyzer/blob/main/src/include/KUNAI/mjolnIR/Analysis/optimizer.hpp. For doing that, it can also be used the `ReachingDefinition` class to know *def-use* and *use-def* chains: https://github.com/Fare9/KUNAI-static-analyzer/blob/main/src/include/KUNAI/mjolnIR/Analysis/reachingDefinition.hpp
Since no more comments have been added around this, I close the issue.
