### ISSUE TITLE
Include a CONTRIBUTING file

### ISSUE THREAD

**Issue by Fare9** [Fare9/KUNAI-static-analyzer#62]
Write a CONTRIBUTING file for helping developers to understand how they can contribute to the project. In this file there must be the branches where we commonly write the new features of the library, or those where we fix the errors instead of directly working on main branch, also the file should contain a short coding style guide to keep as much as possible the same style in the project.

This should have been written long ago... (I'm a disaster... :D)

**Comment by EidanGar** [comment]
@Fare9 is this issue up for grabs?

**Comment by Fare9** [comment]
Hey, nobody has gone with this issue yet so it's free for the moment!

**Comment by EidanGar** [comment]
@Fare9, What do you think of these requirements?
If you're adding a new feature, create a branch named `feature/your-feature-name`. If you're fixing a bug, create a branch named `bugfix/your-bug-name`.

And this coding style guide?
- Use `snake_case` for variable and function names
- Use `PascalCase` for class and struct names.
- Use `UPPERCASE_WITH_UNDERSCORES` for macros.
- Use spaces instead of tabs, with a tab width of 4 spaces.
- Use C++11 style of initializing variables, i.e., `int x{5}` instead of `int x = 5`.
- Use smart pointers (`std::unique_ptr`, `std::shared_ptr`) instead of raw pointers whenever possible.
- Use `nullptr` instead of `NULL`.
- Use `#pragma once` instead of include guards.

I have the CONTRIBUTING.md file complete but I'm not sure about the specific requirements and style guide.

**Comment by Fare9** [comment]
This issue is resolved with next commit: https://github.com/Fare9/KUNAI-static-analyzer/commit/651573c2c97f797922db9cfde73a9480b1ab6d31. Pull request has been accepted, thank you very much for your time @EidanGar , it is really appreciated the contribution.
