### ISSUE TITLE
linker error ostream operator << to print DEX header

### ISSUE THREAD

**Issue by sunniAngela** [Fare9/KUNAI-static-analyzer#68]
When trying to print a DEX header through std::cout and the overloaded operator << that is implemented in kunai-lib/lib/DEX/parser/header.cpp, it gives an error while compiling. Error message is the following: 

```console
undefined reference to `KUNAI::DEX::operator<<(std::ostream&, KUNAI::DEX::Header const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Fare9** [comment]
The next commit should fix for the class `Header`: https://github.com/Fare9/KUNAI-static-analyzer/commit/a2773d8e4affa55ab12395fbc313895c7c97f3e1
In this case, this would only fix it for that class, a fix should be applied for all the other classes that are using operator overloading. Since the linker cannot find the function as the function in the `.cpp` file is not inside of the namespace.
For fixing the issues in the other cases, it would be needed just to include the function of overloading inside of the namespace.

**Comment by Fare9** [comment]
The next commit fix the issue for the strings, but also solves a critical bug Kunai had regarding offset strings, due to reallocation on vector: https://github.com/Fare9/KUNAI-static-analyzer/commit/7333e77144ea7d75baeaf5157f7ac373f60c42fb. I think you also found a segmentation fault on it, so thanks @sunniAngela

**Comment by Fare9** [comment]
Few classes more are already fixed this problem: https://github.com/Fare9/KUNAI-static-analyzer/commit/1034e226af4b8f7c1cebcd4d0b6a0d5e013cc9c6. The task now will be implement similar things for other classes for printing useful headers information :D
